# Generated by Django 5.1.6 on 2025-03-19 17:45

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PDFBookApp', '0002_customuser'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='users_who_marked',
            field=models.ManyToManyField(blank=True, related_name='marked_books', to=settings.AUTH_USER_MODEL),
        ),
    ]
