# Generated by Django 5.1.6 on 2025-03-19 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PDFBookApp', '0003_book_users_who_marked'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='users_who_marked',
        ),
        migrations.AddField(
            model_name='customuser',
            name='marked_books',
            field=models.ManyToManyField(blank=True, related_name='marked_by', to='PDFBookApp.book'),
        ),
    ]
